version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run buildProduction
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'  # This matches the folder where your build outputs are located
